
export const teachers = [
  { id: "t1", name: "Alex Johnson", image: "https://i.ibb.co/L5T199H/teacher1.png", bio: "Passionate about making math fun and accessible for all children. With over 10 years of experience, Alex specializes in interactive and engaging lessons that build a strong foundation in core mathematical concepts.", rating: 4.8, coursesCount: 4 },
  { id: "t2", name: "Sarah Williams", image: "https://i.ibb.co/3sX8c0p/teacher2.png", bio: "An English language expert dedicated to fostering a love for reading and writing. Sarah's creative approach to teaching phonics and grammar helps children become confident communicators and storytellers.", rating: 4.9, coursesCount: 5 },
  { id: "t3", name: "David Chen", image: "https://i.ibb.co/hZ2p4q8/teacher3.png", bio: "A software engineer who simplifies complex coding concepts for young learners. David's courses use project-based learning to teach logical thinking and problem-solving through game development and app creation.", rating: 4.7, coursesCount: 3 },
  { id: "t4", name: "Emily Davis", image: "https://i.ibb.co/T1c9Q9F/teacher4.png", bio: "An inspiring art teacher who believes every child is an artist. Emily guides students through various mediums, from watercolor to digital art, helping them express their unique creativity and build a portfolio of their work.", rating: 5.0, coursesCount: 4 },
  { id: "t5", name: "Michael Brown", image: "https://i.ibb.co/LgL2g2C/teacher5.png", bio: "A science enthusiast who brings science to life with exciting experiments. Michael's hands-on approach encourages curiosity and critical thinking, covering topics from biology to physics in a fun and memorable way.", rating: 4.6, coursesCount: 3 },
  { id: "t6", name: "Jessica White", image: "https://i.ibb.co/d2xL5Yx/teacher6.png", bio: "A professional musician with a heart for teaching. Jessica's music courses cover everything from basic notes to composing simple tunes, helping children discover the joy of music and rhythm.", rating: 4.9, coursesCount: 3 },
  { id: "t7", name: "Chris Lee", image: "https://i.ibb.co/G0S8T97/teacher7.png", bio: "A history buff who makes the past feel like an adventure. Chris uses engaging storytelling and interactive projects to transport students to different eras, from ancient civilizations to modern history.", rating: 4.8, coursesCount: 2 },
  { id: "t8", name: "Anna Rodriguez", image: "https://i.ibb.co/c8G2J7P/teacher8.png", bio: "A Spanish language expert who makes learning a new language a cultural journey. Anna's lessons focus on conversational skills, songs, and cultural activities that make learning fun and effective.", rating: 4.7, coursesCount: 3 },
  { id: "t9", name: "Robert Taylor", image: "https://i.ibb.co/G3Xm8tG/teacher9.png", bio: "A skilled robotics instructor. Robert guides kids through building and programming their own robots, teaching them about mechanics, electronics, and problem-solving in a hands-on environment.", rating: 4.9, coursesCount: 2 },
  { id: "t10", name: "Maria Garcia", image: "https://i.ibb.co/hLqJt5S/teacher10.png", bio: "A talented digital art instructor. Maria's courses help students master digital tools and software, creating vibrant characters, landscapes, and illustrations.", rating: 5.0, coursesCount: 3 },
  { id: "t11", name: "James Wilson", image: "https://i.ibb.co/y4L2q4Y/teacher11.png", bio: "An experienced fitness coach for kids. James's courses promote a healthy and active lifestyle through fun exercises, games, and sports, teaching children about teamwork and physical well-being.", rating: 4.5, coursesCount: 2 },
  { id: "t12", name: "Lisa Adams", image: "https://i.ibb.co/R2tS5x5/teacher12.png", bio: "A creative writing mentor. Lisa inspires young authors to develop their voice and craft compelling stories, focusing on character development, plot structure, and descriptive language.", rating: 4.7, coursesCount: 3 },
  { id: "t13", name: "Ben Carter", image: "https://i.ibb.co/z5p1D2d/teacher13.png", bio: "A photography and videography teacher. Ben teaches kids how to use cameras to capture beautiful moments and tell visual stories, covering composition, lighting, and editing.", rating: 4.8, coursesCount: 2 },
  { id: "t14", name: "Olivia Green", image: "https://i.ibb.co/hH4B1J1/teacher14.png", bio: "An expert in culinary arts for kids. Olivia's courses teach children about healthy cooking and baking, focusing on kitchen safety, measuring ingredients, and creating delicious recipes.", rating: 4.9, coursesCount: 2 },
  { id: "t15", name: "Mark Miller", image: "https://i.ibb.co/f4y1g1f/teacher15.png", bio: "A fantastic physics teacher who uses simple machines and everyday objects to explain complex concepts. Mark's lessons are hands-on and encourage a love for scientific discovery.", rating: 4.6, coursesCount: 2 },
];

export const getTeacherById = (id) => {
  return teachers.find(teacher => teacher.id === id);
};